Repository plotly/dash, pull requests merged in 2024-10, with the labels that each got.

#2991 Added support for URL decoding of the search parameter for pages
  CHANGELOG.md
  dash/_pages.py
Labels: P3, fix, community

#3025 Fix no output callback and error handler.
  CHANGELOG.md
  dash/_callback.py
Labels: P2, fix

#3028 Allow jupyterlab v4 in dependency constraints
  @plotly/dash-jupyterlab/package.json
  @plotly/dash-jupyterlab/tsconfig.json
Labels: feature, P2, community

#3009 Performance improvement on (pattern-matching) callbacks
  CHANGELOG.md
  components/dash-core-components/tests/integration/graph/test_graph_basics.py
  components/dash-core-components/tests/integration/graph/test_graph_varia.py
  dash/dash-renderer/src/actions/dependencies_ts.ts
  dash/dash-renderer/src/observers/prioritizedCallbacks.ts
Labels: performance, P2, fix, community

#2939 Fixes bug with whitespace on DataTable when merge_duplicate_header=True
  CHANGELOG.md
  components/dash-table/src/dash-table/components/ControlledTable/index.tsx
Labels: P2, fix, community
