Repository plotly/dash, pull requests merged in 2024-09, with the labels that each got.

#2909 Rehighlights dcc.Markdown when it is updated
  components/dash-core-components/src/fragments/Markdown.react.js
  components/dash-core-components/tests/integration/misc/test_markdown_highlight.py
Labels: feature, P2

#2980 Version 2.18.0
  CHANGELOG.md
  components/dash-core-components/package-lock.json
  components/dash-core-components/package.json
  components/dash-html-components/package-lock.json
  components/dash-html-components/package.json
  components/dash-table/package-lock.json
  components/dash-table/package.json
  dash/_dash_renderer.py
  dash/dash-renderer/package-lock.json
  dash/dash-renderer/package.json
  dash/version.py
Labels: feature, P1

#2987 Fix multioutput requiring same number of no_update.
  CHANGELOG.md
  dash/_callback.py
  tests/integration/callbacks/test_missing_outputs.py
  tests/integration/renderer/test_dependencies.py
Labels: sev-2, P1, fix

#2841 fix some typing issues
  CHANGELOG.md
  dash/_jupyter.py
  dash/dash.py
  package-lock.json
Labels: P2, fix, community
