Repository plotly/dash, pull requests merged in 2024-08, with the labels that each got.

#2915 Fixes 'AttributeError' when layout is a function that returns a list of components in dash layout setter
  CHANGELOG.md
  dash/dash.py
Labels: P2, fix

#2956 🐛 add missing useEffect dependency to dcc.Loading component
  CHANGELOG.md
  components/dash-core-components/src/components/Loading.react.js
Labels: P1, fix

#2936 Add Support for TypeScript 5.5
  CHANGELOG.md
  dash/extract-meta.js
Labels: feature, P2

#2893 Made CONTRIBUTING guide more (windows-)user friendly
  CONTRIBUTING.md
Labels: documentation, feature, P2, community
