Repository plotly/dash, pull requests merged in 2025-03, with the labels that each got.

#3195 Change to use GET request when requesting dash version from server
  components/dash-table/tests/selenium/test_header.py
  dash/_configs.py
  dash/dash-renderer/src/components/error/menu/VersionInfo.react.js
  dash/dash.py
  dash/testing/application_runners.py
  tests/integration/callbacks/test_missing_outputs.py
  tests/integration/devtools/test_devtools_ui.py
Labels: feature, P1

#3171 JupyterDash Fix - Alive Check
  dash/_jupyter.py
Labels: P2, fix, community

#3190 fix cache key issue
  CHANGELOG.md
  dash/_callback.py
  dash/long_callback/managers/__init__.py
  dash/long_callback/managers/celery_manager.py
  dash/long_callback/managers/diskcache_manager.py
Labels: feature, P2, community

#3237 admin: removing Alex Johnson from code owners
  .github/CODEOWNERS
Labels: infrastructure
