Repository plotly/dash, pull requests merged in 2025-05, with the labels that each got.

#3294 adds `allow_optional` to State and Input to place no value as the placeholders
  CHANGELOG.md
  dash/dash-renderer/src/actions/callbacks.ts
  dash/dependencies.py
  tests/integration/callbacks/test_callback_optional.py
Labels: feature, P1, community

#3300 Add dev_only to proptype.js message
  dash/development/_generate_prop_types.py
Labels: P1, fix

#1906 Make graph height more responsive
  components/dash-core-components/src/fragments/Graph.react.js
  components/dash-core-components/tests/integration/graph/test_graph_responsive.py
Labels: P1, fix, cs

#3108 changed typecheck for list value to use isinstance instead of type
  dash/dash.py
Labels: P1, fix, community

#3068 Create Checklist and RadioItems labels with titles
  CHANGELOG.md
  components/dash-core-components/src/components/Checklist.react.js
  components/dash-core-components/src/components/RadioItems.react.js
  components/dash-core-components/tests/integration/dropdown/test_option_title_prop.py
  components/dash-core-components/tests/integration/test_title_props.py
Labels: feature, P1, community
