Repository plotly/dash, pull requests merged in 2025-01, with the labels that each got.

#3122 Fixed bug in that user specified host/port/proxy were being overwritten
  dash/dash.py
Labels: P1, fix, community

#3093 Default to react 18
  .circleci/config.yml
  @plotly/dash-generator-test-component-nested/src/components/MyNestedComponent.js
  @plotly/dash-generator-test-component-standard/src/components/MyStandardComponent.js
  @plotly/dash-test-components/src/components/AsyncComponent.js
  @plotly/dash-test-components/src/components/CollapseComponent.js
  @plotly/dash-test-components/src/components/DelayedEventComponent.js
  @plotly/dash-test-components/src/components/FragmentComponent.js
  @plotly/dash-test-components/src/components/StyledComponent.js
  @plotly/dash-test-components/src/components/WidthComponent.js
  @plotly/dash-test-components/src/fragments/AsyncComponent.js
  components/dash-core-components/.eslintrc
  components/dash-core-components/package-lock.json
  components/dash-core-components/package.json
  components/dash-core-components/src/fragments/Graph.react.js
  components/dash-core-components/src/utils/ResizeDetector.js
  components/dash-core-components/tests/integration/sliders/test_sliders_shorthands.py
  components/dash-table/package-lock.json
  components/dash-table/package.json
  components/dash-table/src/core/components/IsolatedInput/index.tsx
  components/dash-table/src/dash-table/components/Cell/index.tsx
  components/dash-table/src/dash-table/components/CellDropdown/index.tsx
  components/dash-table/src/dash-table/components/CellInput/index.tsx
  components/dash-table/src/dash-table/components/CellLabel/index.tsx
  components/dash-table/src/dash-table/components/CellMarkdown/index.tsx
  components/dash-table/src/dash-table/components/ControlledTable/fragments/TableTooltip.tsx
  components/dash-table/src/dash-table/components/ControlledTable/index.tsx
  components/dash-table/src/dash-table/components/Tooltip/index.tsx
  dash/_dash_renderer.py
  dash/dash-renderer/package-lock.json
  dash/dash-renderer/package.json
  dash/dash-renderer/src/AppProvider.react.tsx
  dash/development/build_process.py
  package.json
Labels: infrastructure, feature, P1, dependencies

#3130 Fix run host/port default arguments
  dash/dash.py
Labels: feature, P1
