Repository plotly/dash, pull requests merged in 2025-04, with the labels that each got.

#3248 Adjusting memoization on the `DashWrapper` to be utilized
  @plotly/dash-test-components/src/components/RenderType.js
  @plotly/dash-test-components/src/index.js
  CHANGELOG.md
  dash/dash-renderer/src/actions/callbacks.ts
  dash/dash-renderer/src/observers/executedCallbacks.ts
  dash/dash-renderer/src/reducers/reducer.js
  dash/dash-renderer/src/utils/clientsideFunctions.ts
  dash/dash-renderer/src/wrapper/DashWrapper.tsx
  dash/dash-renderer/src/wrapper/selectors.ts
  dash/dash-renderer/src/wrapper/wrapping.ts
  tests/integration/renderer/test_component_as_prop.py
  tests/integration/renderer/test_render_type.py
  tests/integration/test_patch.py
Labels: P1, fix, community

#3263 Add note on params that only work with background callbacks
  dash/_callback.py
Labels: documentation, feature, P1

#3265 localizing the scope of the resize handler
  CHANGELOG.md
  components/dash-core-components/src/utils/ResizeDetector.js
  components/dash-core-components/tests/integration/graph/test_graph_responsive.py
  tests/integration/callbacks/test_prevent_update.py
Labels: P1, fix, community

#3254 feat: adding more type annotations
  components/dash-core-components/dash_core_components_base/__init__.py
  components/dash-table/dash_table_base/__init__.py
  components/dash-table/src/dash-table/dash/DataTable.js
  dash/_callback.py
  dash/_callback_context.py
  dash/_grouping.py
  dash/_hooks.py
  dash/_jupyter.py
  dash/_pages.py
  dash/_patch.py
  dash/_utils.py
  dash/_watch.py
  dash/background_callback/_proxy_set_props.py
  dash/background_callback/managers/celery_manager.py
  dash/background_callback/managers/diskcache_manager.py
  dash/dash.py
  dash/dependencies.py
  dash/development/_jl_components_generation.py
  dash/development/_py_components_generation.py
  dash/development/_py_prop_typing.py
  dash/development/_r_components_generation.py
  dash/development/base_component.py
  dash/development/component_generator.py
  dash/testing/application_runners.py
  dash/testing/browser.py
  dash/testing/dash_page.py
  dash/testing/plugin.py
  tests/integration/test_typing.py
  tests/unit/development/metadata_test.py
Labels: P1, fix

#3273 Fix dash_hooks plugin entry point
  CHANGELOG.md
  dash/_hooks.py
Labels: P1, fix

#3282 Fix incorrect cancellation of pattern matched long callbacks
  CHANGELOG.md
  dash/dash-renderer/src/actions/callbacks.ts
Labels: P1, fix, community
