Repository plotly/dash, pull requests merged in 2025-06, with the labels that each got.

#2927 Fix unexpected behaviour of the cursor
  components/dash-core-components/src/components/Input.react.js
  components/dash-core-components/tests/integration/input/test_input_basics.py
Labels: P2, fix

#3333 update flask
  .lintstagedrc.js
  components/dash-core-components/tests/integration/calendar/test_date_picker_single.py
  components/dash-core-components/tests/integration/graph/test_graph_varia.py
  components/dash-core-components/tests/integration/store/test_data_lifecycle.py
  components/dash-core-components/tests/integration/tab/test_tabs_with_graphs.py
  requirements/install.txt
  tests/async_tests/test_async_callbacks.py
  tests/integration/callbacks/test_basic_callback.py
Labels: feature, P1

#3341 Fix query string parsing regression introduced in 2.18.2 #3106
  CHANGELOG.md
  dash/_pages.py
Labels: regression, P1, fix, community
